name = "SpatialTranscriptomicsGPs"
uuid = "e145bb07-96d9-421f-b0a2-c579a69b21bf"
authors = ["tmichoel <11647967+tmichoel@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
